require('dotenv').load();
var mongoose = require('mongoose');

mongoose.connect(process.env.MONGODB);

var Post = mongoose.connection.collection('posts');

var posts = [
  {
    "title": "Cross-Dimensional Televisions",
    "body": "I find television to be excruciatingly boring. You see the same stuff over and over again. That's why I decided to build a television that has access to all channels across all dimensions. Such a television literally Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis elementum mi vitae justo suscipit, sed malesuada dui volutpat. Vestibulum nec est quam. Nunc ultricies bibendum orci. Nulla facilisi. Quisque nunc justo, lobortis et faucibus nec, feugiat a sem. Quisque lacinia id ipsum consectetur sodales. Sed non nibh id tellus sagittis consectetur vitae eu elit. Donec quis nulla ac lorem mattis posuere. Vivamus sagittis mauris congue, tempus sem vitae, tristique sapien.\n\n## Big Heading\n\nFusce vulputate tristique augue, a euismod sapien porttitor sit amet. In ornare dolor justo, ut ullamcorper justo pretium id. [Quisque](http://google.com) nec risus nec orci tincidunt sodales vel eget lectus. Vivamus et consectetur tortor. Morbi id massa eget sem egestas auctor. Aenean vehicula, dolor vel gravida tincidunt, tortor mi dictum elit, eu iaculis neque risus ac metus. Morbi a ligula placerat dolor iaculis imperdiet a vitae urna. Nam at auctor orci, sed suscipit orci. Etiam ac sem et elit consequat accumsan eu eu tortor. Praesent vulputate bibendum nibh, at cursus enim sodales at. Mauris ornare, felis id pellentesque congue, augue elit malesuada tortor, ut sodales libero dolor et purus. Etiam lobortis consectetur ligula sed vulputate.\n\n### Sub Heading\n\nAenean vulputate efficitur egestas. Nullam blandit eros nec malesuada malesuada. Quisque ac quam condimentum magna interdum sagittis in in sapien. Vestibulum at faucibus enim, sed egestas lectus. Nulla vestibulum orci nibh, et dignissim metus faucibus ac. Phasellus et feugiat dolor, eget tincidunt sem. Cras in tortor eget velit interdum gravida. Duis id ipsum finibus, elementum metus a, ultrices ipsum. Praesent vulputate mi iaculis nulla commodo maximus. Etiam scelerisque, nulla non mollis commodo, magna ipsum semper erat, vel commodo felis nisi sed dolor. Nulla porta mauris eget velit sagittis, nec dignissim sem interdum. Vestibulum faucibus blandit quam, vel vehicula justo lobortis quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend lacinia placerat.\n\nNunc in blandit quam. Sed sed dui nec nisi accumsan ultricies id vel tellus. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent sollicitudin lorem sed dui porta suscipit ac ut ex. Suspendisse potenti. Mauris vel erat massa. Praesent a ligula vitae metus condimentum luctus. Aliquam nibh mauris, facilisis ut lacus ac, rutrum elementum purus. Phasellus eget placerat ex. Sed sed massa ut nulla egestas volutpat. Aenean ac justo convallis urna pulvinar lobortis eget sed mi.\n",
    "url": "cross-dimensional-televisions",
    "created_at": new Date("2015-09-23T21:42:42.819Z")
  },
  { 
    "title": "Concentrated Dark Matter",
    "body": "Concentrated Dark Matter was a fuel that I invented to travel faster than anyone else in the universe. The Zigerions wanted the secret to making this fuel badly, and constantly tried to trick my grandson and I Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis elementum mi vitae justo suscipit, sed malesuada dui volutpat. Vestibulum nec est quam. Nunc ultricies bibendum orci. Nulla facilisi. Quisque nunc justo, lobortis et faucibus nec, feugiat a sem. Quisque lacinia id ipsum consectetur sodales. Sed non nibh id tellus sagittis consectetur vitae eu elit. Donec quis nulla ac lorem mattis posuere. Vivamus sagittis mauris congue, tempus sem vitae, tristique sapien.\n\n## Big Heading\n\nFusce vulputate tristique augue, a euismod sapien porttitor sit amet. In ornare dolor justo, ut ullamcorper justo pretium id. [Quisque](http://google.com) nec risus nec orci tincidunt sodales vel eget lectus. Vivamus et consectetur tortor. Morbi id massa eget sem egestas auctor. Aenean vehicula, dolor vel gravida tincidunt, tortor mi dictum elit, eu iaculis neque risus ac metus. Morbi a ligula placerat dolor iaculis imperdiet a vitae urna. Nam at auctor orci, sed suscipit orci. Etiam ac sem et elit consequat accumsan eu eu tortor. Praesent vulputate bibendum nibh, at cursus enim sodales at. Mauris ornare, felis id pellentesque congue, augue elit malesuada tortor, ut sodales libero dolor et purus. Etiam lobortis consectetur ligula sed vulputate.\n\n### Sub Heading\n\nAenean vulputate efficitur egestas. Nullam blandit eros nec malesuada malesuada. Quisque ac quam condimentum magna interdum sagittis in in sapien. Vestibulum at faucibus enim, sed egestas lectus. Nulla vestibulum orci nibh, et dignissim metus faucibus ac. Phasellus et feugiat dolor, eget tincidunt sem. Cras in tortor eget velit interdum gravida. Duis id ipsum finibus, elementum metus a, ultrices ipsum. Praesent vulputate mi iaculis nulla commodo maximus. Etiam scelerisque, nulla non mollis commodo, magna ipsum semper erat, vel commodo felis nisi sed dolor. Nulla porta mauris eget velit sagittis, nec dignissim sem interdum. Vestibulum faucibus blandit quam, vel vehicula justo lobortis quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend lacinia placerat.\n\nNunc in blandit quam. Sed sed dui nec nisi accumsan ultricies id vel tellus. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent sollicitudin lorem sed dui porta suscipit ac ut ex. Suspendisse potenti. Mauris vel erat massa. Praesent a ligula vitae metus condimentum luctus. Aliquam nibh mauris, facilisis ut lacus ac, rutrum elementum purus. Phasellus eget placerat ex. Sed sed massa ut nulla egestas volutpat. Aenean ac justo convallis urna pulvinar lobortis eget sed mi.\n",
    "url": "concentrated-dark-matter",
    "created_at": new Date("2015-09-22T21:42:42.819Z")
  },
  {
    "title": "Mega Tree Seeds",
    "body": "Dimension 35-C has the perfect conditions for growing Mega Trees. The seeds can be used to briefly make someone incredibly intelligent. Unfortunately in order to get past intergalactic customs, Morty had to hide Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis elementum mi vitae justo suscipit, sed malesuada dui volutpat. Vestibulum nec est quam. Nunc ultricies bibendum orci. Nulla facilisi. Quisque nunc justo, lobortis et faucibus nec, feugiat a sem. Quisque lacinia id ipsum consectetur sodales. Sed non nibh id tellus sagittis consectetur vitae eu elit. Donec quis nulla ac lorem mattis posuere. Vivamus sagittis mauris congue, tempus sem vitae, tristique sapien.\n\n## Big Heading\n\nFusce vulputate tristique augue, a euismod sapien porttitor sit amet. In ornare dolor justo, ut ullamcorper justo pretium id. [Quisque](http://google.com) nec risus nec orci tincidunt sodales vel eget lectus. Vivamus et consectetur tortor. Morbi id massa eget sem egestas auctor. Aenean vehicula, dolor vel gravida tincidunt, tortor mi dictum elit, eu iaculis neque risus ac metus. Morbi a ligula placerat dolor iaculis imperdiet a vitae urna. Nam at auctor orci, sed suscipit orci. Etiam ac sem et elit consequat accumsan eu eu tortor. Praesent vulputate bibendum nibh, at cursus enim sodales at. Mauris ornare, felis id pellentesque congue, augue elit malesuada tortor, ut sodales libero dolor et purus. Etiam lobortis consectetur ligula sed vulputate.\n\n### Sub Heading\n\nAenean vulputate efficitur egestas. Nullam blandit eros nec malesuada malesuada. Quisque ac quam condimentum magna interdum sagittis in in sapien. Vestibulum at faucibus enim, sed egestas lectus. Nulla vestibulum orci nibh, et dignissim metus faucibus ac. Phasellus et feugiat dolor, eget tincidunt sem. Cras in tortor eget velit interdum gravida. Duis id ipsum finibus, elementum metus a, ultrices ipsum. Praesent vulputate mi iaculis nulla commodo maximus. Etiam scelerisque, nulla non mollis commodo, magna ipsum semper erat, vel commodo felis nisi sed dolor. Nulla porta mauris eget velit sagittis, nec dignissim sem interdum. Vestibulum faucibus blandit quam, vel vehicula justo lobortis quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend lacinia placerat.\n\nNunc in blandit quam. Sed sed dui nec nisi accumsan ultricies id vel tellus. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent sollicitudin lorem sed dui porta suscipit ac ut ex. Suspendisse potenti. Mauris vel erat massa. Praesent a ligula vitae metus condimentum luctus. Aliquam nibh mauris, facilisis ut lacus ac, rutrum elementum purus. Phasellus eget placerat ex. Sed sed massa ut nulla egestas volutpat. Aenean ac justo convallis urna pulvinar lobortis eget sed mi.\n",
    "url": "mega-tree-seeds",
    "created_at": new Date("2015-09-21T21:42:42.819Z")
  }
];


Post.drop();

posts.forEach(function(post) {
  Post.insert(post);
});

// hack hack hack
setTimeout(function() {
  process.exit();
}, 5000);
